/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.AgreementParams;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayOpenOperationOpenbizmockRzonegroovyQueryModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayOpenOperationOpenbizmockRzonegroovyQueryModel {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AGREEMENT_PARAMS = "agreement_params";
  @SerializedName(SERIALIZED_NAME_AGREEMENT_PARAMS)
  private AgreementParams agreementParams;

  public static final String SERIALIZED_NAME_UID = "uid";
  @SerializedName(SERIALIZED_NAME_UID)
  private String uid;

  public AlipayOpenOperationOpenbizmockRzonegroovyQueryModel() { 
  }

  public AlipayOpenOperationOpenbizmockRzonegroovyQueryModel agreementParams(AgreementParams agreementParams) {
    
    this.agreementParams = agreementParams;
    return this;
  }

   /**
   * Get agreementParams
   * @return agreementParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AgreementParams getAgreementParams() {
    return agreementParams;
  }


  public void setAgreementParams(AgreementParams agreementParams) {
    this.agreementParams = agreementParams;
  }


  public AlipayOpenOperationOpenbizmockRzonegroovyQueryModel uid(String uid) {
    
    this.uid = uid;
    return this;
  }

   /**
   * 测试
   * @return uid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2088502410932130", value = "测试")

  public String getUid() {
    return uid;
  }


  public void setUid(String uid) {
    this.uid = uid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayOpenOperationOpenbizmockRzonegroovyQueryModel alipayOpenOperationOpenbizmockRzonegroovyQueryModel = (AlipayOpenOperationOpenbizmockRzonegroovyQueryModel) o;
    return Objects.equals(this.agreementParams, alipayOpenOperationOpenbizmockRzonegroovyQueryModel.agreementParams) &&
        Objects.equals(this.uid, alipayOpenOperationOpenbizmockRzonegroovyQueryModel.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementParams, uid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayOpenOperationOpenbizmockRzonegroovyQueryModel {\n");
    sb.append("    agreementParams: ").append(toIndentedString(agreementParams)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("agreement_params");
    openapiFields.add("uid");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayOpenOperationOpenbizmockRzonegroovyQueryModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayOpenOperationOpenbizmockRzonegroovyQueryModel is not found in the empty JSON string", AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AlipayOpenOperationOpenbizmockRzonegroovyQueryModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `agreement_params`
      if (jsonObj.getAsJsonObject("agreement_params") != null) {
        AgreementParams.validateJsonObject(jsonObj.getAsJsonObject("agreement_params"));
      }
      if (jsonObj.get("uid") != null && !jsonObj.get("uid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayOpenOperationOpenbizmockRzonegroovyQueryModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayOpenOperationOpenbizmockRzonegroovyQueryModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayOpenOperationOpenbizmockRzonegroovyQueryModel>() {
           @Override
           public void write(JsonWriter out, AlipayOpenOperationOpenbizmockRzonegroovyQueryModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayOpenOperationOpenbizmockRzonegroovyQueryModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayOpenOperationOpenbizmockRzonegroovyQueryModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayOpenOperationOpenbizmockRzonegroovyQueryModel
  * @throws IOException if the JSON string is invalid with respect to AlipayOpenOperationOpenbizmockRzonegroovyQueryModel
  */
  public static AlipayOpenOperationOpenbizmockRzonegroovyQueryModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayOpenOperationOpenbizmockRzonegroovyQueryModel.class);
  }

 /**
  * Convert an instance of AlipayOpenOperationOpenbizmockRzonegroovyQueryModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

