/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.UserDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_RESULT_EXTRA_JSON = "result_extra_json";
  @SerializedName(SERIALIZED_NAME_RESULT_EXTRA_JSON)
  private String resultExtraJson;

  public static final String SERIALIZED_NAME_RESULT_EXTRA_JSON_ONE = "result_extra_json_one";
  @SerializedName(SERIALIZED_NAME_RESULT_EXTRA_JSON_ONE)
  private String resultExtraJsonOne;

  public static final String SERIALIZED_NAME_RESULT_EXTRA_JSON_ONE_ORIGINAL = "result_extra_json_one_original";
  @SerializedName(SERIALIZED_NAME_RESULT_EXTRA_JSON_ONE_ORIGINAL)
  private String resultExtraJsonOneOriginal;

  public static final String SERIALIZED_NAME_RESULT_EXTRA_JSON_ORIGINAL = "result_extra_json_original";
  @SerializedName(SERIALIZED_NAME_RESULT_EXTRA_JSON_ORIGINAL)
  private String resultExtraJsonOriginal;

  public static final String SERIALIZED_NAME_RESULT_TEST = "result_test";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST)
  private String resultTest;

  public static final String SERIALIZED_NAME_RESULT_TEST_JSON = "result_test_json";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST_JSON)
  private String resultTestJson;

  public static final String SERIALIZED_NAME_RESULT_TEST_JSON_ORIGINAL = "result_test_json_original";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST_JSON_ORIGINAL)
  private String resultTestJsonOriginal;

  public static final String SERIALIZED_NAME_RESULT_TEST_ORIGINAL = "result_test_original";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST_ORIGINAL)
  private String resultTestOriginal;

  public static final String SERIALIZED_NAME_RESULT_TEST_WRONG = "result_test_wrong";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST_WRONG)
  private String resultTestWrong;

  public static final String SERIALIZED_NAME_RESULT_TEST_WRONG_ORIGINAL = "result_test_wrong_original";
  @SerializedName(SERIALIZED_NAME_RESULT_TEST_WRONG_ORIGINAL)
  private String resultTestWrongOriginal;

  public static final String SERIALIZED_NAME_RESULT_USER_DETAIL = "result_user_detail";
  @SerializedName(SERIALIZED_NAME_RESULT_USER_DETAIL)
  private UserDetail resultUserDetail;

  public static final String SERIALIZED_NAME_RESULT_USER_DETAIL_ORIGINAL = "result_user_detail_original";
  @SerializedName(SERIALIZED_NAME_RESULT_USER_DETAIL_ORIGINAL)
  private String resultUserDetailOriginal;

  public static final String SERIALIZED_NAME_RESULT_USER_ID = "result_user_id";
  @SerializedName(SERIALIZED_NAME_RESULT_USER_ID)
  private String resultUserId;

  public static final String SERIALIZED_NAME_RESULT_USER_ID_OPENID = "result_user_id_openid";
  @SerializedName(SERIALIZED_NAME_RESULT_USER_ID_OPENID)
  private String resultUserIdOpenid;

  public static final String SERIALIZED_NAME_RESULT_USER_ID_ORIGINAL = "result_user_id_original";
  @SerializedName(SERIALIZED_NAME_RESULT_USER_ID_ORIGINAL)
  private String resultUserIdOriginal;

  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel() { 
  }

  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultExtraJson(String resultExtraJson) {
    
    this.resultExtraJson = resultExtraJson;
    return this;
  }

   /**
   * 1
   * @return resultExtraJson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{}", value = "1")

  public String getResultExtraJson() {
    return resultExtraJson;
  }


  public void setResultExtraJson(String resultExtraJson) {
    this.resultExtraJson = resultExtraJson;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultExtraJsonOne(String resultExtraJsonOne) {
    
    this.resultExtraJsonOne = resultExtraJsonOne;
    return this;
  }

   /**
   * 1
   * @return resultExtraJsonOne
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ceshi", value = "1")

  public String getResultExtraJsonOne() {
    return resultExtraJsonOne;
  }


  public void setResultExtraJsonOne(String resultExtraJsonOne) {
    this.resultExtraJsonOne = resultExtraJsonOne;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultExtraJsonOneOriginal(String resultExtraJsonOneOriginal) {
    
    this.resultExtraJsonOneOriginal = resultExtraJsonOneOriginal;
    return this;
  }

   /**
   * ceshi
   * @return resultExtraJsonOneOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ceshi")

  public String getResultExtraJsonOneOriginal() {
    return resultExtraJsonOneOriginal;
  }


  public void setResultExtraJsonOneOriginal(String resultExtraJsonOneOriginal) {
    this.resultExtraJsonOneOriginal = resultExtraJsonOneOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultExtraJsonOriginal(String resultExtraJsonOriginal) {
    
    this.resultExtraJsonOriginal = resultExtraJsonOriginal;
    return this;
  }

   /**
   * 1
   * @return resultExtraJsonOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "1")

  public String getResultExtraJsonOriginal() {
    return resultExtraJsonOriginal;
  }


  public void setResultExtraJsonOriginal(String resultExtraJsonOriginal) {
    this.resultExtraJsonOriginal = resultExtraJsonOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTest(String resultTest) {
    
    this.resultTest = resultTest;
    return this;
  }

   /**
   * 1
   * @return resultTest
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "1")

  public String getResultTest() {
    return resultTest;
  }


  public void setResultTest(String resultTest) {
    this.resultTest = resultTest;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTestJson(String resultTestJson) {
    
    this.resultTestJson = resultTestJson;
    return this;
  }

   /**
   * ceshi
   * @return resultTestJson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{}", value = "ceshi")

  public String getResultTestJson() {
    return resultTestJson;
  }


  public void setResultTestJson(String resultTestJson) {
    this.resultTestJson = resultTestJson;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTestJsonOriginal(String resultTestJsonOriginal) {
    
    this.resultTestJsonOriginal = resultTestJsonOriginal;
    return this;
  }

   /**
   * 2
   * @return resultTestJsonOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "2")

  public String getResultTestJsonOriginal() {
    return resultTestJsonOriginal;
  }


  public void setResultTestJsonOriginal(String resultTestJsonOriginal) {
    this.resultTestJsonOriginal = resultTestJsonOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTestOriginal(String resultTestOriginal) {
    
    this.resultTestOriginal = resultTestOriginal;
    return this;
  }

   /**
   * 1
   * @return resultTestOriginal
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "1")

  public String getResultTestOriginal() {
    return resultTestOriginal;
  }


  public void setResultTestOriginal(String resultTestOriginal) {
    this.resultTestOriginal = resultTestOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTestWrong(String resultTestWrong) {
    
    this.resultTestWrong = resultTestWrong;
    return this;
  }

   /**
   * ceshi
   * @return resultTestWrong
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ceshi")

  public String getResultTestWrong() {
    return resultTestWrong;
  }


  public void setResultTestWrong(String resultTestWrong) {
    this.resultTestWrong = resultTestWrong;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultTestWrongOriginal(String resultTestWrongOriginal) {
    
    this.resultTestWrongOriginal = resultTestWrongOriginal;
    return this;
  }

   /**
   * ceshi
   * @return resultTestWrongOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "ceshi")

  public String getResultTestWrongOriginal() {
    return resultTestWrongOriginal;
  }


  public void setResultTestWrongOriginal(String resultTestWrongOriginal) {
    this.resultTestWrongOriginal = resultTestWrongOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultUserDetail(UserDetail resultUserDetail) {
    
    this.resultUserDetail = resultUserDetail;
    return this;
  }

   /**
   * Get resultUserDetail
   * @return resultUserDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserDetail getResultUserDetail() {
    return resultUserDetail;
  }


  public void setResultUserDetail(UserDetail resultUserDetail) {
    this.resultUserDetail = resultUserDetail;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultUserDetailOriginal(String resultUserDetailOriginal) {
    
    this.resultUserDetailOriginal = resultUserDetailOriginal;
    return this;
  }

   /**
   * 4
   * @return resultUserDetailOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "4")

  public String getResultUserDetailOriginal() {
    return resultUserDetailOriginal;
  }


  public void setResultUserDetailOriginal(String resultUserDetailOriginal) {
    this.resultUserDetailOriginal = resultUserDetailOriginal;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultUserId(String resultUserId) {
    
    this.resultUserId = resultUserId;
    return this;
  }

   /**
   * 1
   * @return resultUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "1")

  public String getResultUserId() {
    return resultUserId;
  }


  public void setResultUserId(String resultUserId) {
    this.resultUserId = resultUserId;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultUserIdOpenid(String resultUserIdOpenid) {
    
    this.resultUserIdOpenid = resultUserIdOpenid;
    return this;
  }

   /**
   * 1
   * @return resultUserIdOpenid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "074a1CcTG1LelxKe4xQC0zgNdId0nxi95b5lsNpazWYoCo5", value = "1")

  public String getResultUserIdOpenid() {
    return resultUserIdOpenid;
  }


  public void setResultUserIdOpenid(String resultUserIdOpenid) {
    this.resultUserIdOpenid = resultUserIdOpenid;
  }


  public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel resultUserIdOriginal(String resultUserIdOriginal) {
    
    this.resultUserIdOriginal = resultUserIdOriginal;
    return this;
  }

   /**
   * 1
   * @return resultUserIdOriginal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "1")

  public String getResultUserIdOriginal() {
    return resultUserIdOriginal;
  }


  public void setResultUserIdOriginal(String resultUserIdOriginal) {
    this.resultUserIdOriginal = resultUserIdOriginal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel = (AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel) o;
    return Objects.equals(this.resultExtraJson, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultExtraJson) &&
        Objects.equals(this.resultExtraJsonOne, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultExtraJsonOne) &&
        Objects.equals(this.resultExtraJsonOneOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultExtraJsonOneOriginal) &&
        Objects.equals(this.resultExtraJsonOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultExtraJsonOriginal) &&
        Objects.equals(this.resultTest, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTest) &&
        Objects.equals(this.resultTestJson, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTestJson) &&
        Objects.equals(this.resultTestJsonOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTestJsonOriginal) &&
        Objects.equals(this.resultTestOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTestOriginal) &&
        Objects.equals(this.resultTestWrong, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTestWrong) &&
        Objects.equals(this.resultTestWrongOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultTestWrongOriginal) &&
        Objects.equals(this.resultUserDetail, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultUserDetail) &&
        Objects.equals(this.resultUserDetailOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultUserDetailOriginal) &&
        Objects.equals(this.resultUserId, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultUserId) &&
        Objects.equals(this.resultUserIdOpenid, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultUserIdOpenid) &&
        Objects.equals(this.resultUserIdOriginal, alipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.resultUserIdOriginal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultExtraJson, resultExtraJsonOne, resultExtraJsonOneOriginal, resultExtraJsonOriginal, resultTest, resultTestJson, resultTestJsonOriginal, resultTestOriginal, resultTestWrong, resultTestWrongOriginal, resultUserDetail, resultUserDetailOriginal, resultUserId, resultUserIdOpenid, resultUserIdOriginal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel {\n");
    sb.append("    resultExtraJson: ").append(toIndentedString(resultExtraJson)).append("\n");
    sb.append("    resultExtraJsonOne: ").append(toIndentedString(resultExtraJsonOne)).append("\n");
    sb.append("    resultExtraJsonOneOriginal: ").append(toIndentedString(resultExtraJsonOneOriginal)).append("\n");
    sb.append("    resultExtraJsonOriginal: ").append(toIndentedString(resultExtraJsonOriginal)).append("\n");
    sb.append("    resultTest: ").append(toIndentedString(resultTest)).append("\n");
    sb.append("    resultTestJson: ").append(toIndentedString(resultTestJson)).append("\n");
    sb.append("    resultTestJsonOriginal: ").append(toIndentedString(resultTestJsonOriginal)).append("\n");
    sb.append("    resultTestOriginal: ").append(toIndentedString(resultTestOriginal)).append("\n");
    sb.append("    resultTestWrong: ").append(toIndentedString(resultTestWrong)).append("\n");
    sb.append("    resultTestWrongOriginal: ").append(toIndentedString(resultTestWrongOriginal)).append("\n");
    sb.append("    resultUserDetail: ").append(toIndentedString(resultUserDetail)).append("\n");
    sb.append("    resultUserDetailOriginal: ").append(toIndentedString(resultUserDetailOriginal)).append("\n");
    sb.append("    resultUserId: ").append(toIndentedString(resultUserId)).append("\n");
    sb.append("    resultUserIdOpenid: ").append(toIndentedString(resultUserIdOpenid)).append("\n");
    sb.append("    resultUserIdOriginal: ").append(toIndentedString(resultUserIdOriginal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("result_extra_json");
    openapiFields.add("result_extra_json_one");
    openapiFields.add("result_extra_json_one_original");
    openapiFields.add("result_extra_json_original");
    openapiFields.add("result_test");
    openapiFields.add("result_test_json");
    openapiFields.add("result_test_json_original");
    openapiFields.add("result_test_original");
    openapiFields.add("result_test_wrong");
    openapiFields.add("result_test_wrong_original");
    openapiFields.add("result_user_detail");
    openapiFields.add("result_user_detail_original");
    openapiFields.add("result_user_id");
    openapiFields.add("result_user_id_openid");
    openapiFields.add("result_user_id_original");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("result_test");
    openapiRequiredFields.add("result_test_original");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel is not found in the empty JSON string", AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("result_extra_json") != null && !jsonObj.get("result_extra_json").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_extra_json` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_extra_json").toString()));
      }
      if (jsonObj.get("result_extra_json_one") != null && !jsonObj.get("result_extra_json_one").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_extra_json_one` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_extra_json_one").toString()));
      }
      if (jsonObj.get("result_extra_json_one_original") != null && !jsonObj.get("result_extra_json_one_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_extra_json_one_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_extra_json_one_original").toString()));
      }
      if (jsonObj.get("result_extra_json_original") != null && !jsonObj.get("result_extra_json_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_extra_json_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_extra_json_original").toString()));
      }
      if (jsonObj.get("result_test") != null && !jsonObj.get("result_test").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test").toString()));
      }
      if (jsonObj.get("result_test_json") != null && !jsonObj.get("result_test_json").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test_json` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test_json").toString()));
      }
      if (jsonObj.get("result_test_json_original") != null && !jsonObj.get("result_test_json_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test_json_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test_json_original").toString()));
      }
      if (jsonObj.get("result_test_original") != null && !jsonObj.get("result_test_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test_original").toString()));
      }
      if (jsonObj.get("result_test_wrong") != null && !jsonObj.get("result_test_wrong").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test_wrong` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test_wrong").toString()));
      }
      if (jsonObj.get("result_test_wrong_original") != null && !jsonObj.get("result_test_wrong_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_test_wrong_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_test_wrong_original").toString()));
      }
      // validate the optional field `result_user_detail`
      if (jsonObj.getAsJsonObject("result_user_detail") != null) {
        UserDetail.validateJsonObject(jsonObj.getAsJsonObject("result_user_detail"));
      }
      if (jsonObj.get("result_user_detail_original") != null && !jsonObj.get("result_user_detail_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_user_detail_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_user_detail_original").toString()));
      }
      if (jsonObj.get("result_user_id") != null && !jsonObj.get("result_user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_user_id").toString()));
      }
      if (jsonObj.get("result_user_id_openid") != null && !jsonObj.get("result_user_id_openid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_user_id_openid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_user_id_openid").toString()));
      }
      if (jsonObj.get("result_user_id_original") != null && !jsonObj.get("result_user_id_original").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result_user_id_original` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result_user_id_original").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel>() {
           @Override
           public void write(JsonWriter out, AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
  * @throws IOException if the JSON string is invalid with respect to AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
  */
  public static AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel.class);
  }

 /**
  * Convert an instance of AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

