/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.api;

import com.alipay.v3.ApiException;
import com.alipay.v3.ApiClient;
import com.alipay.v3.util.model.AlipayConfig;
import com.alipay.v3.Configuration;
import com.alipay.v3.model.AlipayOpenFileUploadDefaultResponse;
import com.alipay.v3.model.AlipayOpenFileUploadModel;
import com.alipay.v3.model.AlipayOpenFileUploadResponseModel;
import java.io.File;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlipayOpenFileApi
 */
@Disabled
public class AlipayOpenFileApiTest {

    private final AlipayOpenFileApi api = new AlipayOpenFileApi();

    @BeforeEach
    public void setUp() throws ApiException {
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        //初始化alipay参数（全局设置一次）
        AlipayConfig config = new AlipayConfig();
        config.setAppId("2021003126677278");
        config.setPrivateKey("MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvPSL+jltaVtR0e9nm4c3YKs9r+26HbX6Q5ZL9rKMFPP5lLspWxs2wgLS/PuqqwSr96n5DDLvqTqwQGQCP8XGBexKacmpzozENKjYexsViNeGcZicO2+VeJlXembIk+aQ0pnpIj9RA8Yopj+V54rsA7ZoVU3o8/gizsyhyb8PbBkGbFr4h/PkeONOD6F9Q1Zkti9m3V1mp6vKwGmktciVD0vOD4kB3uF7aNw+6AmdnFa/z9K+5b5UoBRjqKdBP8DWUymqnFdn/zzsJPk/mi/XDUfmt5CBh+oMC9clos25b+OTNjKVif2twks+S8VipOc/FN/ZJfZZ7lfizO1oAh823AgMBAAECggEABavb2xMuX7EZtR9hAPjj2ZAhIGSFwjpH81aKuE0DBaNgtFOcVsyeUY0IzHuzyozv4EHbjj32QvIC3Y6BlycAPmmGQ5taWJ26c6ufDsXuE2yc/ZvMvc1eEfr5onek7U9rAg01Pe3xt5xZlVjD23r8BF6sMu59sUWjcHVm5LU7SHZQqXcFg/hQk6BJHM6cKjP+IZJQXwwuMj1B9+P0dRShpMQvQeG/VNz3ZTwsx83YRhHWiSgzsExAsEknFqxFmzhLR4YyPhF7KL5TbHFqIPWPXdlPIclY4DJU/ujsH9PutgzVMlBFRSU+J74h4cnfsSNtBuRwggu+cOmnYgaes9toKQKBgQDVeRGPY7JPCs5cd+aU38tUrvDDT6UHfXjWTwlYTAPw1WKPSzIiL8q5C3tjcW/XgaGA8P8r7h18bXhvn9L6ypGUQDXF2JVMUcNrgiYEKBNjd9ogDoqUpWAtUAk0Gu2mWEVKpnqRFVP7rwGqiIuiQ/ck2KgfyLC3SbD0qbDGBq0AKwKBgQDSJimD1hbwkgti//iAHUG/icboYCWO1X0RvWjkVrzu3IlAm4nzuL6qP8IRbkaDWqNNq102fMDmF2KdABEJe3wFK12DV2glIORSg0CKOGnOmCaAiTRKfooEcKvDrpC63EnXVCe8BWnNDqh8EsFDnEjNpYkHz1gZK9km1j6SOokWpQKBgQDO49NdAOajLHnrrFjRGERcAmBdKidrJvOh4F/SL3nyQxyOe/ZOo7r5tGMVca9PUddQvEDSNqhlG0OKC3/Sh9inscNryAiKOwQGgdCOXrjLwjCouO8eOVkJEXSaBy8j9JDTVJ2dVupaFraqrEOINA6mq0Pl6f865DSYKo2knnu0mQKBgHItJ8soS4hjYOpl9obs3mcJnVdtvZowJea4iT/eXIJOsge3OimAC5+GSpOb3ZXKbgVqAJf1Cf05YWu5uIf1XnmUiRcuKzhY+ZRXGX6/jcUgZ3LYmN+MhsJI0RndQ2cy/q+OWpROQKCXwTTAH97zD58jvCLRJaVvbGksaAyc3xS9AoGAfP5LTFxwM9tX7axAyMMgZCAq108OF4EiM5JVWutLl223fc1+zSNwzYKcrtNKIQXSgKCT8kL1EThETlPbZHpBEQv4s02nVusxMNO4cAfmwJFwzv2jmfX0YjKYuMHtLekSPUshFPZ/NMrSY41G82Um5DY+phzuh6QR8igaXo3YCE4=");
        config.setAlipayPublicKey("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlr+2Mir816Ye8ybsC8QgIigrG2oqVTwYeCjiJQPGP0x7iRVVwQuuM54rO+OyyfJcvI5UWFtfcpy+si+3JyaInKP69DA0AS4XkVPV/81xcIHMZP/CJAYOtLFLhhyEwp1CMoN45BtJes5lG65UXz/7QzVjcF+6AC+qVKx66HKSsT9b5HyWRxfDkOYixy1gZt39w+sgxaAPVt6pf7UZHX+ENE/gYpTCHHflVPzPfl8TIXTZmEMGqjBLY8GFXVJkvATX3h12VX3AwUlIndY4gJND9l1isFV9BfpmZYyv864z14UH6Kq9u8WVWdF5bsJevo4oU0Q0UB8EmyOdlxBPTDiOzwIDAQAB");
    //        config.setAppCertPath("src/test/resources/fixture/appCertPublicKey_2021003126695331.crt");
    //        config.setAlipayPublicCertPath("src/test/resources/fixture/alipayCertPublicKey_RSA2.crt");
    //        config.setRootCertPath("src/test/resources/fixture/alipayRootCert.crt");
        config.setEncryptKey("wEA0iV4eLSTV+o5/T9RKjg==");

        defaultClient.setAlipayConfig(config);
    }

    /**
     * 支付宝文件上传接口
     *
     * 支付宝通用文件上传接口，支付宝开发者可以调用此接口上传文件，文件可以提供给其他业务使用，例如：上传素材（视频/图片），素材可以供给到生活号+/小程序等其他开放应用后正式发布。 该接口支持使用支付宝SDK和HTTP POST请求，两种方式示例如下： 1. 使用支付宝SDK时，可以直接使用FileItem上传，代码片段参考下文 2. 使用直接使用http协议时，需要忽略file_content参数，文件放入表单中，其余参数放入URL中，其中将参数（不包括文件和file_content）按&lt;a href&#x3D;\&quot;https://opendocs.alipay.com/common/02kf5q#%E8%87%AA%E8%A1%8C%E5%AE%9E%E7%8E%B0%E7%AD%BE%E5%90%8D\&quot;&gt;自行实现签名&lt;/a&gt;文档实现，示例： curl --request POST &#39;http://openapi.alipay.com/gateway.do?charset&#x3D;GBK&amp;biz_content&#x3D;%7B%22biz_code%22%3A%22content_creation%22%2C%22extra_parameters%22%3A%7B%22extern_upload%22%3A%22youku%22%2C%22alipay_user_id%22%3A%22xxxx%22%7D%7D&amp;method&#x3D;alipay.open.file.upload&amp;format&#x3D;json&amp;sign&#x3D;xxx&amp;app_id&#x3D;2014060600164699&amp;version&#x3D;1.0&amp;sign_type&#x3D;RSA2&amp;timestamp&#x3D;xxx&#39;  --form &#39;file&#x3D;@\&quot;xx.mp4\&quot;&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadTest() throws ApiException {
        
        String returnUrl = new String();
        
        String notifyUrl = new String();
        
        AlipayOpenFileUploadModel data = new AlipayOpenFileUploadModel();
        File fileContent = null;
        
        AlipayOpenFileUploadResponseModel response = api.upload(returnUrl, notifyUrl, data, fileContent);
        // TODO: test validations
    }

}
