/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgreementParams
 */
public class AgreementParamsTest {
    private final AgreementParams model = new AgreementParams();

    /**
     * Model tests for AgreementParams
     */
    @Test
    public void testAgreementParams() {
        // TODO: test AgreementParams
    }

    /**
     * Test the property 'agreementNo'
     */
    @Test
    public void agreementNoTest() {
        // TODO: test agreementNo
    }

    /**
     * Test the property 'applyToken'
     */
    @Test
    public void applyTokenTest() {
        // TODO: test applyToken
    }

    /**
     * Test the property 'authConfirmNo'
     */
    @Test
    public void authConfirmNoTest() {
        // TODO: test authConfirmNo
    }

    /**
     * Test the property 'deductPermission'
     */
    @Test
    public void deductPermissionTest() {
        // TODO: test deductPermission
    }

}
