/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.alipay.v3.model.UserDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
 */
public class AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModelTest {
    private final AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel model = new AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel();

    /**
     * Model tests for AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
     */
    @Test
    public void testAlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel() {
        // TODO: test AlipayOpenOperationOpenbizmockOpenidtestingQueryResponseModel
    }

    /**
     * Test the property 'resultExtraJson'
     */
    @Test
    public void resultExtraJsonTest() {
        // TODO: test resultExtraJson
    }

    /**
     * Test the property 'resultExtraJsonOne'
     */
    @Test
    public void resultExtraJsonOneTest() {
        // TODO: test resultExtraJsonOne
    }

    /**
     * Test the property 'resultExtraJsonOneOriginal'
     */
    @Test
    public void resultExtraJsonOneOriginalTest() {
        // TODO: test resultExtraJsonOneOriginal
    }

    /**
     * Test the property 'resultExtraJsonOriginal'
     */
    @Test
    public void resultExtraJsonOriginalTest() {
        // TODO: test resultExtraJsonOriginal
    }

    /**
     * Test the property 'resultTest'
     */
    @Test
    public void resultTestTest() {
        // TODO: test resultTest
    }

    /**
     * Test the property 'resultTestJson'
     */
    @Test
    public void resultTestJsonTest() {
        // TODO: test resultTestJson
    }

    /**
     * Test the property 'resultTestJsonOriginal'
     */
    @Test
    public void resultTestJsonOriginalTest() {
        // TODO: test resultTestJsonOriginal
    }

    /**
     * Test the property 'resultTestOriginal'
     */
    @Test
    public void resultTestOriginalTest() {
        // TODO: test resultTestOriginal
    }

    /**
     * Test the property 'resultTestWrong'
     */
    @Test
    public void resultTestWrongTest() {
        // TODO: test resultTestWrong
    }

    /**
     * Test the property 'resultTestWrongOriginal'
     */
    @Test
    public void resultTestWrongOriginalTest() {
        // TODO: test resultTestWrongOriginal
    }

    /**
     * Test the property 'resultUserDetail'
     */
    @Test
    public void resultUserDetailTest() {
        // TODO: test resultUserDetail
    }

    /**
     * Test the property 'resultUserDetailOriginal'
     */
    @Test
    public void resultUserDetailOriginalTest() {
        // TODO: test resultUserDetailOriginal
    }

    /**
     * Test the property 'resultUserId'
     */
    @Test
    public void resultUserIdTest() {
        // TODO: test resultUserId
    }

    /**
     * Test the property 'resultUserIdOpenid'
     */
    @Test
    public void resultUserIdOpenidTest() {
        // TODO: test resultUserIdOpenid
    }

    /**
     * Test the property 'resultUserIdOriginal'
     */
    @Test
    public void resultUserIdOriginalTest() {
        // TODO: test resultUserIdOriginal
    }

}
