/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.alipay.v3.model.OpenidComplex;
import com.alipay.v3.model.UserDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AlipayOpenOperationOpenbizmockOpenidtestingQueryModel
 */
public class AlipayOpenOperationOpenbizmockOpenidtestingQueryModelTest {
    private final AlipayOpenOperationOpenbizmockOpenidtestingQueryModel model = new AlipayOpenOperationOpenbizmockOpenidtestingQueryModel();

    /**
     * Model tests for AlipayOpenOperationOpenbizmockOpenidtestingQueryModel
     */
    @Test
    public void testAlipayOpenOperationOpenbizmockOpenidtestingQueryModel() {
        // TODO: test AlipayOpenOperationOpenbizmockOpenidtestingQueryModel
    }

    /**
     * Test the property 'extraJson'
     */
    @Test
    public void extraJsonTest() {
        // TODO: test extraJson
    }

    /**
     * Test the property 'extraJson1'
     */
    @Test
    public void extraJson1Test() {
        // TODO: test extraJson1
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'testWrong'
     */
    @Test
    public void testWrongTest() {
        // TODO: test testWrong
    }

    /**
     * Test the property 'userDetail'
     */
    @Test
    public void userDetailTest() {
        // TODO: test userDetail
    }

}
