/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.alipay.v3.model.FileUploadExtraParam;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AlipayOpenFileUploadModel
 */
public class AlipayOpenFileUploadModelTest {
    private final AlipayOpenFileUploadModel model = new AlipayOpenFileUploadModel();

    /**
     * Model tests for AlipayOpenFileUploadModel
     */
    @Test
    public void testAlipayOpenFileUploadModel() {
        // TODO: test AlipayOpenFileUploadModel
    }

    /**
     * Test the property 'bizCode'
     */
    @Test
    public void bizCodeTest() {
        // TODO: test bizCode
    }

    /**
     * Test the property 'extraParameters'
     */
    @Test
    public void extraParametersTest() {
        // TODO: test extraParameters
    }

    /**
     * Test the property 'md5'
     */
    @Test
    public void md5Test() {
        // TODO: test md5
    }

}
