/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AlipayOpenOperationOpenbizmockRzoneQueryResponseModel
 */
public class AlipayOpenOperationOpenbizmockRzoneQueryResponseModelTest {
    private final AlipayOpenOperationOpenbizmockRzoneQueryResponseModel model = new AlipayOpenOperationOpenbizmockRzoneQueryResponseModel();

    /**
     * Model tests for AlipayOpenOperationOpenbizmockRzoneQueryResponseModel
     */
    @Test
    public void testAlipayOpenOperationOpenbizmockRzoneQueryResponseModel() {
        // TODO: test AlipayOpenOperationOpenbizmockRzoneQueryResponseModel
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'resultOpenid'
     */
    @Test
    public void resultOpenidTest() {
        // TODO: test resultOpenid
    }

    /**
     * Test the property 'zoneName'
     */
    @Test
    public void zoneNameTest() {
        // TODO: test zoneName
    }

    /**
     * Test the property 'zoneOpenid'
     */
    @Test
    public void zoneOpenidTest() {
        // TODO: test zoneOpenid
    }

}
