/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FileUploadExtraParam
 */
public class FileUploadExtraParamTest {
    private final FileUploadExtraParam model = new FileUploadExtraParam();

    /**
     * Model tests for FileUploadExtraParam
     */
    @Test
    public void testFileUploadExtraParam() {
        // TODO: test FileUploadExtraParam
    }

    /**
     * Test the property 'externUpload'
     */
    @Test
    public void externUploadTest() {
        // TODO: test externUpload
    }

    /**
     * Test the property 'fileEncryptType'
     */
    @Test
    public void fileEncryptTypeTest() {
        // TODO: test fileEncryptType
    }

}
