/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OpenidComplex
 */
public class OpenidComplexTest {
    private final OpenidComplex model = new OpenidComplex();

    /**
     * Model tests for OpenidComplex
     */
    @Test
    public void testOpenidComplex() {
        // TODO: test OpenidComplex
    }

    /**
     * Test the property 'jsonString'
     */
    @Test
    public void jsonStringTest() {
        // TODO: test jsonString
    }

    /**
     * Test the property 'openIdList'
     */
    @Test
    public void openIdListTest() {
        // TODO: test openIdList
    }

    /**
     * Test the property 'openid'
     */
    @Test
    public void openidTest() {
        // TODO: test openid
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'uidList'
     */
    @Test
    public void uidListTest() {
        // TODO: test uidList
    }

}
